MODE_MANUAL = "manual"
MODE_AUTOMATIC = "automatic"
MODE_TAKEOVER = "takeover"

DRIVE_MANUAL = "manual"
DRIVE_AUTOMATIC = "automatic"

TRAFFIC_VEHICLES = 20
TRAFFIC_PEDESTRIANS = 10
TRAFFIC_MIN_DISTANCE_FROM_EGO = 50.0
TRAFFIC_MIN_DISTANCE_FROM_ROUTE = 80.0
