MODE_MANUAL = "manual"
MODE_AUTOMATIC = "automatic"
MODE_TAKEOVER = "takeover"

DRIVE_MANUAL = "manual"
DRIVE_AUTOMATIC = "automatic"

TRAFFIC_VEHICLES = 4
TRAFFIC_PEDESTRIANS = 3
TRAFFIC_MIN_DISTANCE_FROM_EGO = 50.0
TRAFFIC_MIN_DISTANCE_FROM_ROUTE = 40.0
TRAFFIC_AVOID_ROUTE_ROADS = False

ROUTE_MIN_METERS = 2200.0
ROUTE_MAX_METERS = 5200.0
ROUTE_ATTEMPTS = 25
