MODE_MANUAL = "manual"
MODE_AUTOMATIC = "automatic"
MODE_TAKEOVER = "takeover"

DRIVE_MANUAL = "manual"
DRIVE_AUTOMATIC = "automatic"

TRAFFIC_VEHICLES = 4
TRAFFIC_PEDESTRIANS = 3
TRAFFIC_MIN_DISTANCE_FROM_EGO = 50.0
TRAFFIC_MIN_DISTANCE_FROM_ROUTE = 40.0
TRAFFIC_AVOID_ROUTE_ROADS = False

ROUTE_MIN_METERS = 8000.0
ROUTE_MAX_METERS = 32000.0
ROUTE_ATTEMPTS = 80
ROUTE_MAX_TOTAL_ATTEMPTS = 200
ROUTE_MIN_SECONDS = 300.0
ROUTE_SPEED_KMH = 40.0
ROUTE_STRICT_MIN = False

CARLA_TIMEOUT_SECONDS = 10.0
SIM_SYNC_MODE = False
